### ISSUE TITLE
Discord Cleanup

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/PM#3]
my suggest is so
```
ANN
	news
	roadmap
	vote
	welcome (system)
GENERAL
	general
	help?
	off-topic
	mining
	exchange-listing/trade
	design
BOT
	ALLBOT SHARE
	level-ups
	hashrate-price
INTERNATIONAL SUPPORT
	keep
MUSIC
        keep
DEV
	keep
```

**Comment by cryptozeny** [comment]
> aglkmToday at 1:31 AM
How about removing translator channel? :grinning:

possible

**Comment by cryptozeny** [comment]
remove some unused bots suggested by aglkm

**Comment by aglkm** [comment]
My suggestions.

Remove the following bots as nobody uses them:
CoingeckoPrice Bot
Smoogle Translate
Rythm

Changes to discord channels:
Rename #sugar-news to #announcements
Remove #notifications
All news and notifications will go to #announcements channel

Remove #le-francais and #deutsch channels as nobody uses them since the very beginning (if there will be a demand from the community to open any specific language channel then we will create without problems in the future)

Remove #info channel, it duplicates the #links channel

**Comment by cryptozeny** [comment]
> CoingeckoPrice Bot

agreed

> Smoogle Translate

no, salmaan and i use somtimes

> Rythm

no, i like it. 

> Rename #sugar-news to #announcements

agreed

> Remove #notifications

agreed

> All news and notifications will go to #announcements channel

agreed

> Remove #le-francais and #deutsch channels as nobody uses them since the very beginning (if there will be a demand from the community to open any specific language channel then we will create without problems in the future)

not remove, but move to archive. (only sugar team can see the archive)

> Remove #info channel, it duplicates the #links channel

agreed

@aglkm

**Comment by aglkm** [comment]
Maybe it will be better to rename #info channel to #faq channel and address most frequently asked questions there. I can handle it if you all agree with this.

**Comment by cryptozeny** [comment]
> Maybe it will be better to rename #info channel to #faq channel and address most frequently asked questions there. I can handle it if you all agree with this.

agreed

**Comment by joeland1** [comment]
no more discord so close?

**Comment by cryptozeny** [comment]
closing
